# Generated by Django 5.1.5 on 2025-02-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='weight',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='valeur',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
